#!/bin/sh
#echo "Nome dell'applicazione da creare"
#read APP

if [ $# -eq 0 ]
  then
    echo "No app name  supplied"
    exit 1
fi

APP_NAME="$1"

DIR_TMP="/srv/tmp/"
DIR_WWW="/opt/sites/"
DIR_GIT="/srv/git/"
DIR_ENV="/srv/env/"

GIT=$DIR_GIT$APP_NAME.git
TMP=$DIR_TMP$APP_NAME
WWW=$DIR_WWW$APP_NAME

echo "- git:" "$GIT"
echo "- tmp:" "$TMP"
echo "- www:" "$WWW"

export GIT
export TMP
export WWW

echo "Creating $APPNAME folder git"
sudo mkdir -p "$GIT"

echo "Init the repo as an empty git repository"
cd "$GIT" || exit
sudo git init --bare

echo "Define group to users, recursively"
sudo chgrp -R users

echo "Define permission recursively on sub-directories"
# g = group, + add rights, r = read, w = write, X = directories only
# . = curent directory as a reference
sudo chmod -R g+rwX .

echo "Make the directory a Git shared repo"
sudo git config core.sharedRepository group

cd "$GIT/hooks" || exit

sudo tee post-receive <<EOF
#!/bin/bash

# Cartella di produzione
WWW="${WWW}"
# Cartella temporanea dedicata al deploy
TMP="${TMP}"
# Il repository GIT
REPO="${GIT}"
# Fase di deploy
mkdir -p \$TMP
git --work-tree=\$TMP --git-dir=\$REPO checkout -f
cd \$TMP
# eventuali operazioni prima del deploy es npm install, npm run build…
# … GENERATE_SOURCEMAP=false  npm run build
cd /
rm -rf \$WWW
mv \$TMP \$WWW

EOF

sudo chmod +x post-receive

